include:
  - project: 'personal-websites/pipeline-templates'
    ref: 'main'
    file: '/.ci-templates/docker.gitlab-ci.yml'

variables:
  SHORT_SHA: $CI_COMMIT_SHORT_SHA
  APP_NAME: syaccli
  SYAC_FEATURE_BRANCH_PREFIX: "gmarm-"

stages:
  - setup      # compile + comment logic
  - build      # image build
  - release    # tagging and promotion

# -----------------------------------------------
# Compile syac binary for use in later stages
# -----------------------------------------------
build_binary:
  stage: setup
  image: golang:1.24
  variables:
    SYAC_APPLICATION_NAME: syaccli
  script:
    - CGO_ENABLED=0 go build -o syac -ldflags '-extldflags "-static"' .
  after_script:
    - chmod +x syac
    - ./syac context
  artifacts:
    paths:
      - syac
    expire_in: 1 hour

# -----------------------------------------------
# Build on feature branches — gmarm-* (no push) 
# -----------------------------------------------
build_feature:
  stage: build
  extends: [.build-dind, .build-common]
  variables:
    IMAGE_ENV_PATH: "$CI_REGISTRY_IMAGE/feature/$CI_COMMIT_REF_NAME"
    PUSH_IMAGE: "false"
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^$SYAC_FEATURE_BRANCH_PREFIX\d+$/'

# -----------------------------------------------
# Build on dev — push SHA + latest
# -----------------------------------------------
build_dev:
  stage: build
  extends: [.build-dind, .build-common]
  variables:
    IMAGE_ENV_PATH: "$CI_REGISTRY_IMAGE/dev"
    PUSH_IMAGE: "true"
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
    - when: never